//! G-snapshot reverse decode — flat bytes → mirror → crema AST → `EnvironmentDraft`
//! → frozen [`Environment`] (ADR-0028 slice 1c).
//!
//! Reconstruction goes through `EnvironmentDraft::insert_*` + `build()`
//! rather than assembling a frozen value directly, so the rebuilt
//! environment passes the same identity validation / flatten / normalize
//! passes a cold build does.
//!
//! Two invariants this module leans on:
//!
//! - Symbol / TypeName ids are content-addressed (ADR-0025), so interning
//!   the snapshot's strings into a fresh `NameTable` reproduces the exact
//!   ids stored in the flat tables. Each re-derivation is verified and a
//!   mismatch surfaces as [`RebuildError::CorruptFlat`].
//! - The draft only ever holds top-level declarations (context length 1);
//!   flatten-generated entries (context length >= 2) are regenerated by
//!   `build()` from the parents' member trees. Re-inserting them here
//!   would double-register every nested declaration.

use std::sync::Arc;

use rustc_hash::{FxHashMap, FxHashSet};

use crate::ast::declarations as cd;
use crate::ast::members as cm;
use crate::ast::method_type::MethodType;
use crate::ast::type_param::{TypeParam, Variance};
use crate::ast::types as ct;
use crate::environment::DeclOrigin;
use crate::environment::draft::{Context, EnvironmentDraft};
use crate::environment::frozen::{ClassDeclaration, ClassOrModule, Environment, ModuleDeclaration};
use crate::location as cl;
use crate::name::{Name, NameTable, Symbol};
use crate::snapshot::append_map::AppendMap;
use crate::snapshot::backend::GSnapshotBackend;
use crate::snapshot::convert::sym_id_of;
use crate::snapshot::flat;
use crate::snapshot::invalidation::InvalidationKey;
use crate::snapshot::mirror::*;
use crate::snapshot::write::{G_SNAPSHOT_MAGIC, G_SNAPSHOT_SCHEMA_VERSION, HEADER_LEN};
use crate::type_name::TypeName;

pub struct RebuiltGSnapshot {
    pub env: Environment,
    pub key: InvalidationKey,
}

#[derive(Debug)]
pub enum RebuildError {
    BadMagic,
    UnsupportedSchemaVersion(u32),
    CorruptFlat(String),
    BincodeDecode(bincode::Error),
    RegisterFailure(String),
}

impl std::fmt::Display for RebuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RebuildError::BadMagic => write!(f, "bad snapshot magic"),
            RebuildError::UnsupportedSchemaVersion(v) => {
                write!(f, "unsupported schema version {v}")
            }
            RebuildError::CorruptFlat(msg) => write!(f, "corrupt flat payload: {msg}"),
            RebuildError::BincodeDecode(e) => write!(f, "entry decode failed: {e}"),
            RebuildError::RegisterFailure(msg) => write!(f, "register failure: {msg}"),
        }
    }
}

impl std::error::Error for RebuildError {}

pub(crate) fn corrupt(msg: impl Into<String>) -> RebuildError {
    RebuildError::CorruptFlat(msg.into())
}

/// A context of length 1 (just the root) marks a pair that was inserted
/// top-level at draft time; longer contexts are flatten-generated and
/// must not be re-inserted (see module doc).
fn is_top_level(ctx: &[Tn]) -> bool {
    ctx.len() == 1
}

/// Decode a whole G-snapshot file (64-byte header + flat payload) back
/// into a frozen [`Environment`] plus the invalidation key it was written
/// under. The caller compares the key against the current inputs.
pub fn rebuild(bytes: &[u8]) -> Result<RebuiltGSnapshot, RebuildError> {
    if bytes.len() < HEADER_LEN {
        return Err(corrupt(format!(
            "file shorter than header: {} bytes",
            bytes.len()
        )));
    }
    let magic = u64::from_le_bytes(bytes[0..8].try_into().unwrap());
    if magic != G_SNAPSHOT_MAGIC {
        return Err(RebuildError::BadMagic);
    }
    let version = u32::from_le_bytes(bytes[8..12].try_into().unwrap());
    if version != G_SNAPSHOT_SCHEMA_VERSION {
        return Err(RebuildError::UnsupportedSchemaVersion(version));
    }
    let mut key = [0u8; 32];
    key.copy_from_slice(&bytes[16..48]);
    let key = InvalidationKey(key);

    let reader = flat::Reader::try_open(&bytes[HEADER_LEN..]).map_err(corrupt)?;
    let env = rebuild_env(&reader)?;
    Ok(RebuiltGSnapshot { env, key })
}

fn timing_enabled() -> bool {
    std::env::var_os("CREMA_DEBUG_SNAPSHOT_TIMING").is_some_and(|v| v == "1")
}

fn rebuild_env(reader: &flat::Reader<'_>) -> Result<Environment, RebuildError> {
    let timing = timing_enabled();
    let t0 = std::time::Instant::now();

    let mut draft = EnvironmentDraft::new();

    let mut entry_map: FxHashMap<u64, MEntry> = FxHashMap::default();
    for (id, bytes) in reader.iter_entries() {
        let entry: MEntry = bincode::deserialize(bytes).map_err(RebuildError::BincodeDecode)?;
        entry_map.insert(id, entry);
    }
    let t_decode = t0.elapsed();

    let ops = {
        let tables = DecodeTables::intern_from(reader, draft.names())?;
        let mut dec = Decoder::new(&tables);
        dec.collect_ops(&entry_map)?
    };
    let t_tables = t0.elapsed();

    for op in ops {
        op.apply(&mut draft)
            .map_err(RebuildError::RegisterFailure)?;
    }
    let env = match draft.build() {
        Ok(env) => env,
        Err((e, names)) => {
            return Err(RebuildError::RegisterFailure(e.format_with(&names)));
        }
    };
    if timing {
        eprintln!(
            "g-snapshot: rebuild breakdown: entry decode {:.1}ms, tables+ast {:.1}ms, insert+build {:.1}ms",
            t_decode.as_secs_f64() * 1000.0,
            (t_tables - t_decode).as_secs_f64() * 1000.0,
            (t0.elapsed() - t_tables).as_secs_f64() * 1000.0,
        );
    }
    Ok(env)
}

/// Recursively register the flat type-name chain for `id` into `names`'
/// overlay `TypeNameInterner`, verifying the content-addressed recipe
/// reproduces the stored id (the inverse of `convert::Cx::tn`'s drift
/// check).
///
/// `visited` is a memo scoped to one [`DecodeTables::intern_from`] call.
/// Unlike the id-to-`TypeName` lookup table this function's predecessor
/// (ADR-0028 F2) used to build, it only needs to remember "already
/// walked" to skip re-registering a shared prefix, not the resulting
/// `TypeName`: any raw id reconstructs directly via `TypeName::from_hash`
/// (content addressing, ADR-0025).
fn ensure_tn_registered(
    id: u64,
    reader: &flat::Reader<'_>,
    names: &NameTable,
    visited: &mut FxHashSet<u64>,
    depth: usize,
) -> Result<(), RebuildError> {
    if visited.contains(&id) {
        return Ok(());
    }
    if depth > 4096 {
        return Err(corrupt("type-name parent chain too deep (cyclic?)"));
    }
    let (parent, seg, absolute) = reader
        .tn_entry(id)
        .ok_or_else(|| corrupt(format!("missing type-name entry {id:#x}")))?;
    let t = if parent == 0 {
        names.type_name_root(absolute)
    } else {
        ensure_tn_registered(parent, reader, names, visited, depth + 1)?;
        let p = TypeName::from_hash(parent);
        let seg_str = reader
            .sym_str(seg)
            .ok_or_else(|| corrupt(format!("missing segment symbol {seg:#x}")))?;
        let sym = names.intern_symbol(seg_str);
        names.append_type_name(p, sym)
    };
    if t.get() != id {
        return Err(corrupt(format!("type-name recipe drift for {id:#x}")));
    }
    visited.insert(id);
    Ok(())
}

/// Deferred draft insertion — decoding borrows the draft's `NameTable`
/// immutably, so inserts are collected first and applied after that
/// borrow ends.
enum InsertOp {
    Class(DeclOrigin, Context, Arc<cd::ClassDeclaration>),
    Module(DeclOrigin, Context, Arc<cd::ModuleDeclaration>),
    Interface(DeclOrigin, Context, Arc<cd::InterfaceDeclaration>),
    TypeAlias(DeclOrigin, Context, Arc<cd::TypeAliasDeclaration>),
    Constant(DeclOrigin, Context, Arc<cd::ConstantDeclaration>),
    Global(DeclOrigin, Context, Arc<cd::GlobalDeclaration>),
    ClassAlias(DeclOrigin, Context, Arc<cd::ClassAliasDeclaration>),
    ModuleAlias(DeclOrigin, Context, Arc<cd::ModuleAliasDeclaration>),
}

impl InsertOp {
    fn apply(self, draft: &mut EnvironmentDraft) -> Result<(), String> {
        let format = |draft: &EnvironmentDraft, e: crate::environment::draft::BuildError| {
            e.format_with(draft.names())
        };
        match self {
            InsertOp::Class(f, c, d) => draft
                .insert_class_decl(f, c, d)
                .map_err(|e| format(draft, e)),
            InsertOp::Module(f, c, d) => draft
                .insert_module_decl(f, c, d)
                .map_err(|e| format(draft, e)),
            InsertOp::Interface(f, c, d) => draft
                .insert_interface_decl(f, c, d)
                .map_err(|e| format(draft, e)),
            InsertOp::TypeAlias(f, c, d) => draft
                .insert_type_alias(f, c, d)
                .map_err(|e| format(draft, e)),
            InsertOp::Constant(f, c, d) => {
                draft.insert_constant(f, c, d).map_err(|e| format(draft, e))
            }
            InsertOp::Global(f, c, d) => draft.insert_global(f, c, d).map_err(|e| format(draft, e)),
            InsertOp::ClassAlias(f, c, d) => draft
                .insert_class_alias(f, c, d)
                .map_err(|e| format(draft, e)),
            InsertOp::ModuleAlias(f, c, d) => draft
                .insert_module_alias(f, c, d)
                .map_err(|e| format(draft, e)),
        }
    }
}

/// Common decoded fields shared by Include / Extend / Prepend members.
struct MixinFields {
    name: TypeName,
    args: Vec<ct::Type>,
    annotations: Vec<crate::ast::annotation::Annotation>,
    location: Option<cl::MixinMemberLocation>,
    source_file: Option<Name>,
    comment: Option<crate::ast::comment::Comment>,
}

/// Common decoded fields shared by AttrReader / AttrWriter / AttrAccessor.
struct AttrFields {
    name: Symbol,
    ty: ct::Type,
    ivar_name: cm::IvarName,
    kind: cm::AttributeKind,
    annotations: Vec<crate::ast::annotation::Annotation>,
    location: Option<cl::AttributeMemberLocation>,
    source_file: Option<Name>,
    comment: Option<crate::ast::comment::Comment>,
    visibility: Option<crate::ast::Visibility>,
}

/// Common decoded fields shared by the three variable-member kinds.
struct VarFields {
    name: Symbol,
    ty: ct::Type,
    location: Option<cl::VariableMemberLocation>,
    source_file: Option<Name>,
    comment: Option<crate::ast::comment::Comment>,
}

/// The snapshot-local `NameId` → interned [`Name`] remap table shared by
/// every mirror → AST decode. Symbol / TypeName ids need no such table
/// (ADR-0025 content addressing): [`Decoder::sym`]/[`Decoder::tn`]
/// reconstruct them directly from their raw id.
pub(crate) struct DecodeTables {
    pub(crate) name_by_id: Vec<Name>,
}

impl DecodeTables {
    /// Intern every name / symbol / type-name of the flat payload into
    /// `names`, verifying the content-addressed recipes. O(names +
    /// symbols + type-names) — independent of entry count and of entry
    /// payload bytes.
    pub(crate) fn intern_from(
        reader: &flat::Reader<'_>,
        names: &NameTable,
    ) -> Result<Self, RebuildError> {
        let name_by_id: Vec<Name> = (0..reader.names_len() as u32)
            .map(|i| names.intern(reader.name_str(i)))
            .collect();

        for (id, s) in reader.iter_symbols() {
            if sym_id_of(s) != id {
                return Err(corrupt(format!("symbol id drift for {s:?}")));
            }
            names.intern_symbol(s);
        }

        let mut visited: FxHashSet<u64> = FxHashSet::default();
        for (id, _) in reader.iter_type_names() {
            ensure_tn_registered(id, reader, names, &mut visited, 0)?;
        }

        Ok(DecodeTables { name_by_id })
    }
}

/// Where nested-declaration refs fetch their target entry from: the
/// eager rebuild pre-decodes everything into a map; the lazy backend
/// probes the flat entry index and memoizes per-fetch decodes for the
/// memo's (caller-chosen) lifetime, bumping `decodes` on every real
/// deserialization.
pub(crate) enum EntrySource<'a> {
    Map(&'a FxHashMap<u64, MEntry>),
    Flat {
        reader: &'a flat::Reader<'a>,
        memo: &'a AppendMap<u64, MEntry>,
        decodes: &'a std::cell::Cell<usize>,
    },
}

impl EntrySource<'_> {
    pub(crate) fn get(&self, id: u64) -> Result<Option<&MEntry>, RebuildError> {
        match self {
            EntrySource::Map(map) => Ok(map.get(&id)),
            EntrySource::Flat {
                reader,
                memo,
                decodes,
            } => {
                if let Some(e) = memo.get(&id) {
                    return Ok(Some(e));
                }
                let Some(bytes) = reader.lookup_entry(id) else {
                    return Ok(None);
                };
                let entry = memo.get_or_try_insert_with(id, || {
                    decodes.set(decodes.get() + 1);
                    bincode::deserialize(bytes).map_err(RebuildError::BincodeDecode)
                })?;
                Ok(Some(entry))
            }
        }
    }
}

pub(crate) struct Decoder<'t> {
    tables: &'t DecodeTables,
    /// Per-(entry id, expected context) consumption cursor for nested
    /// declaration references. A parent's `MDeclRef` consumes the next
    /// unconsumed pair of the child entry whose context matches
    /// `parent ctx + parent name`, in order — the same order flatten
    /// appended them on the write side.
    cursors: FxHashMap<(u64, Vec<u64>), usize>,
    /// When set, every class/module declaration converted through a
    /// nested-decl ref is also recorded under `(child entry id, pair
    /// index)`. The lazy backend's decode-all pass reuses these Arcs
    /// for the child entries' flatten pairs — restoring the sharing a
    /// draft-flatten build gets for free, instead of re-converting
    /// every nested subtree once per ancestor level.
    nested_out: Option<&'t AppendMap<(u64, usize), cd::Declaration>>,
    depth: usize,
    /// G backend to fall back to when a nested decl ref's target has no
    /// A-layer entry: a parent pulled into the overlay can carry a
    /// `MDeclRef` to a nested child that stayed G-snapshot-only, so the
    /// overlay-only shadow map can't resolve it. `None` for G's own
    /// rebuild, where every real decl is already covered by G's own
    /// entries.
    g: Option<&'t GSnapshotBackend>,
}

impl<'t> Decoder<'t> {
    pub(crate) fn new(tables: &'t DecodeTables) -> Self {
        Decoder {
            tables,
            cursors: FxHashMap::default(),
            nested_out: None,
            depth: 0,
            g: None,
        }
    }

    pub(crate) fn with_nested_cache(
        tables: &'t DecodeTables,
        nested_out: &'t AppendMap<(u64, usize), cd::Declaration>,
    ) -> Self {
        Decoder {
            tables,
            cursors: FxHashMap::default(),
            nested_out: Some(nested_out),
            depth: 0,
            g: None,
        }
    }

    /// Reconstructs the `Symbol` straight from its raw content-addressed
    /// id (ADR-0028 F1) — infallible, but kept `Result`-returning so its
    /// ~30 call sites (each already using `?`) don't need touching. See
    /// [`Symbol::from_raw_id`] for the validity argument.
    pub(crate) fn sym(&self, id: Sym) -> Result<Symbol, RebuildError> {
        Ok(Symbol::from_raw_id(id))
    }

    /// Reconstructs the `TypeName` straight from its raw content-addressed
    /// id (ADR-0028 F2) — infallible, but kept `Result`-returning for
    /// symmetry with [`Self::sym`] and so its many call sites (each
    /// already using `?`) don't need touching. Valid whenever `id` really
    /// is a type-name id written by `convert::Cx::tn` (ADR-0025 content
    /// addressing) — the flat payload's own `flat::Reader::try_open`
    /// validation (plus, on the G path, `ensure_tn_registered`'s
    /// per-name drift check) establishes this before decode reaches a
    /// call site that needs it.
    pub(crate) fn tn(&self, id: Tn) -> Result<TypeName, RebuildError> {
        Ok(TypeName::from_hash(id))
    }

    pub(crate) fn name(&self, id: NameId) -> Result<Name, RebuildError> {
        self.tables
            .name_by_id
            .get(id as usize)
            .copied()
            .ok_or_else(|| corrupt(format!("name id {id} out of range")))
    }

    pub(crate) fn opt_name(&self, id: Option<NameId>) -> Result<Option<Name>, RebuildError> {
        id.map(|i| self.name(i)).transpose()
    }

    pub(crate) fn context(&self, ctx: &[Tn]) -> Result<Context, RebuildError> {
        let v: Vec<TypeName> = ctx.iter().map(|t| self.tn(*t)).collect::<Result<_, _>>()?;
        Ok(Arc::from(v))
    }

    /// Top-level pairs only (context length 1); flatten-generated pairs
    /// are re-derived by `build()` from the parents' member trees.
    fn collect_ops(&mut self, map: &FxHashMap<u64, MEntry>) -> Result<Vec<InsertOp>, RebuildError> {
        let entries = &EntrySource::Map(map);
        let mut ops = Vec::new();
        for entry in map.values() {
            match entry {
                MEntry::ClassOrModule(MClassOrModule::Class(e)) => {
                    for (ctx, d) in &e.context_decls {
                        if !is_top_level(ctx) {
                            continue;
                        }
                        let decl = Arc::new(self.class_decl(entries, d, ctx)?);
                        let file = decl.source_file.into();
                        ops.push(InsertOp::Class(file, self.context(ctx)?, decl));
                    }
                }
                MEntry::ClassOrModule(MClassOrModule::Module(e)) => {
                    for (ctx, d) in &e.context_decls {
                        if !is_top_level(ctx) {
                            continue;
                        }
                        let decl = Arc::new(self.module_decl(entries, d, ctx)?);
                        let file = decl.source_file.into();
                        ops.push(InsertOp::Module(file, self.context(ctx)?, decl));
                    }
                }
                MEntry::Interface(e) => {
                    if !is_top_level(&e.context) {
                        continue;
                    }
                    let decl = Arc::new(self.interface_decl(&e.decl)?);
                    let file = decl.source_file.into();
                    ops.push(InsertOp::Interface(file, self.context(&e.context)?, decl));
                }
                MEntry::ClassAlias(e) => {
                    if !is_top_level(&e.context) {
                        continue;
                    }
                    let ctx = self.context(&e.context)?;
                    match e.kind {
                        0 => {
                            let decl = Arc::new(self.class_alias_decl(&e.decl)?);
                            ops.push(InsertOp::ClassAlias(decl.source_file.into(), ctx, decl));
                        }
                        1 => {
                            let decl = Arc::new(self.module_alias_decl(&e.decl)?);
                            ops.push(InsertOp::ModuleAlias(decl.source_file.into(), ctx, decl));
                        }
                        k => return Err(corrupt(format!("unknown class-alias kind {k}"))),
                    }
                }
                MEntry::TypeAlias(e) => {
                    if !is_top_level(&e.context) {
                        continue;
                    }
                    let decl = Arc::new(self.type_alias_decl(&e.decl)?);
                    let file = decl.source_file.into();
                    ops.push(InsertOp::TypeAlias(file, self.context(&e.context)?, decl));
                }
                MEntry::Constant(e) => {
                    if !is_top_level(&e.context) {
                        continue;
                    }
                    let decl = Arc::new(self.constant_decl(&e.decl)?);
                    ops.push(InsertOp::Constant(
                        DeclOrigin::Unspecified,
                        self.context(&e.context)?,
                        decl,
                    ));
                }
                MEntry::Global(e) => {
                    if !is_top_level(&e.context) {
                        continue;
                    }
                    let decl = Arc::new(self.global_decl(&e.decl)?);
                    let file = self.opt_name(e.file)?.into();
                    ops.push(InsertOp::Global(file, self.context(&e.context)?, decl));
                }
            }
        }
        Ok(ops)
    }

    /// Reconstruct a nested-declaration member slot from its entry
    /// reference (the inverse of `convert::Cx::decl_ref`).
    fn decl_ref(
        &mut self,
        entries: &EntrySource<'_>,
        r: &MDeclRef,
        expected_ctx: &[Tn],
    ) -> Result<cd::Declaration, RebuildError> {
        if self.depth > 64 {
            return Err(corrupt("nested declaration refs too deep (cyclic?)"));
        }
        self.depth += 1;
        let result = self.decl_ref_inner(entries, r, expected_ctx);
        self.depth -= 1;
        result
    }

    fn decl_ref_inner(
        &mut self,
        entries: &EntrySource<'_>,
        r: &MDeclRef,
        expected_ctx: &[Tn],
    ) -> Result<cd::Declaration, RebuildError> {
        let Some(entry) = entries.get(r.id)? else {
            return self.decl_ref_from_g(r, expected_ctx);
        };
        match (r.kind, entry) {
            (0, MEntry::ClassOrModule(MClassOrModule::Class(e))) => {
                let idx = self.consume_pair(
                    r.id,
                    expected_ctx,
                    e.context_decls.iter().map(|(ctx, _)| ctx.as_slice()),
                )?;
                let (ctx, d) = &e.context_decls[idx];
                let decl = cd::Declaration::Class(Arc::new(self.class_decl(entries, d, ctx)?));
                if let Some(cache) = self.nested_out {
                    cache.insert_first((r.id, idx), decl.clone());
                }
                Ok(decl)
            }
            (1, MEntry::ClassOrModule(MClassOrModule::Module(e))) => {
                let idx = self.consume_pair(
                    r.id,
                    expected_ctx,
                    e.context_decls.iter().map(|(ctx, _)| ctx.as_slice()),
                )?;
                let (ctx, d) = &e.context_decls[idx];
                let decl = cd::Declaration::Module(Arc::new(self.module_decl(entries, d, ctx)?));
                if let Some(cache) = self.nested_out {
                    cache.insert_first((r.id, idx), decl.clone());
                }
                Ok(decl)
            }
            (2, MEntry::Interface(e)) => Ok(cd::Declaration::Interface(Arc::new(
                self.interface_decl(&e.decl)?,
            ))),
            (3, MEntry::Constant(e)) => Ok(cd::Declaration::Constant(Arc::new(
                self.constant_decl(&e.decl)?,
            ))),
            (4, MEntry::Global(e)) => Ok(cd::Declaration::Global(Arc::new(
                self.global_decl(&e.decl)?,
            ))),
            (5, MEntry::TypeAlias(e)) => Ok(cd::Declaration::TypeAlias(Arc::new(
                self.type_alias_decl(&e.decl)?,
            ))),
            (6, MEntry::ClassAlias(e)) if e.kind == 0 => Ok(cd::Declaration::ClassAlias(Arc::new(
                self.class_alias_decl(&e.decl)?,
            ))),
            (7, MEntry::ClassAlias(e)) if e.kind == 1 => Ok(cd::Declaration::ModuleAlias(
                Arc::new(self.module_alias_decl(&e.decl)?),
            )),
            (k, _) => Err(corrupt(format!(
                "nested decl ref kind {k} does not match entry {:#x}",
                r.id
            ))),
        }
    }

    /// Cross-layer fallback for a nested decl ref with no A-layer entry
    /// (ADR-0028 S6b follow-up, see the `g` field doc): a parent pulled
    /// into the A layer (touched/reopened) can embed a `MDeclRef` to a
    /// nested child that received no A-side edit of its own and so
    /// stayed G-snapshot-only — `entries` (the A-only shadow/entry map)
    /// never has an entry for it. G's own decls carry no `MDeclRef`
    /// indirection (G's own rebuild already resolved it), so this reads
    /// the target directly off the attached backend instead of going
    /// through the mirror/entry layer. `consume_pair` still
    /// disambiguates multiple G-side pairs sharing the same context
    /// (e.g. the same nested name reopened by several G-only files),
    /// sharing cursor state with the A-side lookups.
    ///
    /// `self.g` is `None` for G's own rebuild, where every real decl is
    /// already covered by G's own entries and a miss is genuine
    /// corruption; the `ok_or_else` below reproduces the original
    /// "dangling" error for that case.
    fn decl_ref_from_g(
        &mut self,
        r: &MDeclRef,
        expected_ctx: &[Tn],
    ) -> Result<cd::Declaration, RebuildError> {
        let dangling = || corrupt(format!("dangling nested decl ref {:#x}", r.id));
        let g = self.g.ok_or_else(dangling)?;
        match r.kind {
            0 => {
                let name = self.tn(r.id)?;
                let ClassOrModule::Class(ce) = g.class_entry(&name).ok_or_else(dangling)? else {
                    return Err(corrupt(format!(
                        "nested decl ref kind 0 does not match g entry {:#x}",
                        r.id
                    )));
                };
                let sig: Vec<(Vec<Tn>, &Arc<cd::ClassDeclaration>)> = ce
                    .context_decls()
                    .iter()
                    .filter_map(|(_, ctx, d)| match d {
                        ClassDeclaration::Signature(s) => {
                            Some((ctx.iter().map(|t| t.get()).collect(), s))
                        }
                        ClassDeclaration::Ruby(_) => None,
                    })
                    .collect();
                let idx =
                    self.consume_pair(r.id, expected_ctx, sig.iter().map(|(c, _)| c.as_slice()))?;
                Ok(cd::Declaration::Class(Arc::clone(sig[idx].1)))
            }
            1 => {
                let name = self.tn(r.id)?;
                let ClassOrModule::Module(me) = g.class_entry(&name).ok_or_else(dangling)? else {
                    return Err(corrupt(format!(
                        "nested decl ref kind 1 does not match g entry {:#x}",
                        r.id
                    )));
                };
                let sig: Vec<(Vec<Tn>, &Arc<cd::ModuleDeclaration>)> = me
                    .context_decls()
                    .iter()
                    .filter_map(|(_, ctx, d)| match d {
                        ModuleDeclaration::Signature(s) => {
                            Some((ctx.iter().map(|t| t.get()).collect(), s))
                        }
                        ModuleDeclaration::Ruby(_) => None,
                    })
                    .collect();
                let idx =
                    self.consume_pair(r.id, expected_ctx, sig.iter().map(|(c, _)| c.as_slice()))?;
                Ok(cd::Declaration::Module(Arc::clone(sig[idx].1)))
            }
            2 => {
                let name = self.tn(r.id)?;
                let e = g.interface_entry(&name).ok_or_else(dangling)?;
                Ok(cd::Declaration::Interface(Arc::clone(e.decl())))
            }
            3 => {
                let name = self.tn(r.id)?;
                let e = g.constant_entry(&name).ok_or_else(dangling)?;
                Ok(cd::Declaration::Constant(Arc::clone(&e.decl)))
            }
            4 => {
                let sym = self.sym(r.id)?;
                let e = g.global_entry(&sym).ok_or_else(dangling)?;
                Ok(cd::Declaration::Global(Arc::clone(&e.decl)))
            }
            5 => {
                let name = self.tn(r.id)?;
                let e = g.type_alias_entry(&name).ok_or_else(dangling)?;
                Ok(cd::Declaration::TypeAlias(Arc::clone(&e.decl)))
            }
            k => Err(corrupt(format!(
                "nested decl ref kind {k} has no g fallback for {:#x}",
                r.id
            ))),
        }
    }

    fn consume_pair<'m>(
        &mut self,
        id: u64,
        expected_ctx: &[Tn],
        pair_ctxs: impl Iterator<Item = &'m [Tn]>,
    ) -> Result<usize, RebuildError> {
        let cursor_key = (id, expected_ctx.to_vec());
        let start = self.cursors.get(&cursor_key).copied().unwrap_or(0);
        for (i, ctx) in pair_ctxs.enumerate() {
            if i < start {
                continue;
            }
            if ctx == expected_ctx {
                self.cursors.insert(cursor_key, i + 1);
                return Ok(i);
            }
        }
        Err(corrupt(format!(
            "no unconsumed pair with expected context for nested entry {id:#x}"
        )))
    }

    fn range(&self, r: &MRange) -> cl::LocationRange {
        cl::LocationRange {
            start_char: r.0,
            start_byte: r.1,
            end_char: r.2,
            end_byte: r.3,
        }
    }

    fn opt_range(&self, r: &Option<MRange>) -> Option<cl::LocationRange> {
        r.as_ref().map(|r| self.range(r))
    }

    pub(crate) fn ty(&self, t: &MType) -> Result<ct::Type, RebuildError> {
        Ok(match t {
            MType::Base(b) => ct::Type::Base(ct::BaseType {
                kind: match &b.kind {
                    MBaseTypeKind::Bool => ct::BaseTypeKind::Bool,
                    MBaseTypeKind::Void => ct::BaseTypeKind::Void,
                    MBaseTypeKind::Any { todo } => ct::BaseTypeKind::Any { todo: *todo },
                    MBaseTypeKind::Nil => ct::BaseTypeKind::Nil,
                    MBaseTypeKind::Top => ct::BaseTypeKind::Top,
                    MBaseTypeKind::Bottom => ct::BaseTypeKind::Bottom,
                    MBaseTypeKind::SelfType => ct::BaseTypeKind::SelfType,
                    MBaseTypeKind::Instance => ct::BaseTypeKind::Instance,
                    MBaseTypeKind::Class => ct::BaseTypeKind::Class,
                },
                location: self.opt_range(&b.location),
            }),
            MType::Variable(v) => ct::Type::Variable(ct::VariableType {
                name: self.sym(v.name)?,
                location: self.opt_range(&v.location),
            }),
            MType::ClassSingleton(n) => ct::Type::ClassSingleton(ct::ClassSingletonType {
                name: self.tn(n.name)?,
                args: self.tys(&n.args)?,
                location: n.location.as_ref().map(|l| cl::ClassSingletonLocation {
                    range: self.range(&l.range),
                    name_range: self.range(&l.name_range),
                    args_range: self.opt_range(&l.args_range),
                }),
            }),
            MType::Interface(n) => ct::Type::Interface(ct::InterfaceType {
                name: self.tn(n.name)?,
                args: self.tys(&n.args)?,
                location: n.location.as_ref().map(|l| cl::InterfaceLocation {
                    range: self.range(&l.range),
                    name_range: self.range(&l.name_range),
                    args_range: self.opt_range(&l.args_range),
                }),
            }),
            MType::ClassInstance(n) => ct::Type::ClassInstance(ct::ClassInstanceType {
                name: self.tn(n.name)?,
                args: self.tys(&n.args)?,
                location: n.location.as_ref().map(|l| cl::ClassInstanceLocation {
                    range: self.range(&l.range),
                    name_range: self.range(&l.name_range),
                    args_range: self.opt_range(&l.args_range),
                }),
            }),
            MType::Alias(n) => ct::Type::Alias(ct::AliasType {
                name: self.tn(n.name)?,
                args: self.tys(&n.args)?,
                location: n.location.as_ref().map(|l| cl::AliasLocation {
                    range: self.range(&l.range),
                    name_range: self.range(&l.name_range),
                    args_range: self.opt_range(&l.args_range),
                }),
            }),
            MType::Tuple(t) => ct::Type::Tuple(ct::TupleType {
                types: self.tys(&t.types)?,
                location: self.opt_range(&t.location),
            }),
            MType::Record(r) => ct::Type::Record(ct::RecordType {
                fields: r
                    .fields
                    .iter()
                    .map(|f| {
                        Ok(ct::RecordField {
                            key: match &f.key {
                                MRecordKey::Symbol(s) => ct::RecordKey::Symbol(self.sym(*s)?),
                                MRecordKey::String(s) => ct::RecordKey::String(s.clone()),
                                MRecordKey::Integer(s) => ct::RecordKey::Integer(s.clone()),
                                MRecordKey::Bool(b) => ct::RecordKey::Bool(*b),
                            },
                            ty: self.ty(&f.ty)?,
                            required: f.required,
                        })
                    })
                    .collect::<Result<_, RebuildError>>()?,
                location: self.opt_range(&r.location),
            }),
            MType::Optional(o) => ct::Type::Optional(ct::OptionalType {
                ty: Box::new(self.ty(&o.ty)?),
                location: self.opt_range(&o.location),
            }),
            MType::Union(u) => ct::Type::Union(ct::UnionType {
                types: self.tys(&u.types)?,
                location: self.opt_range(&u.location),
            }),
            MType::Intersection(i) => ct::Type::Intersection(ct::IntersectionType {
                types: self.tys(&i.types)?,
                location: self.opt_range(&i.location),
            }),
            MType::Proc(p) => ct::Type::Proc(Box::new(ct::ProcType {
                function: self.function(&p.function)?,
                block: p.block.as_ref().map(|b| self.block(b)).transpose()?,
                self_type: p
                    .self_type
                    .as_ref()
                    .map(|t| Ok::<_, RebuildError>(Box::new(self.ty(t)?)))
                    .transpose()?,
                location: self.opt_range(&p.location),
            })),
            MType::Literal(l) => ct::Type::Literal(ct::LiteralType {
                literal: match &l.literal {
                    MLiteral::Integer(s) => ct::Literal::Integer(s.clone()),
                    MLiteral::String(s) => ct::Literal::String(s.clone()),
                    MLiteral::Symbol(s) => ct::Literal::Symbol(self.sym(*s)?),
                    MLiteral::Bool(b) => ct::Literal::Bool(*b),
                },
                location: self.opt_range(&l.location),
            }),
        })
    }

    fn tys(&self, ts: &[MType]) -> Result<Vec<ct::Type>, RebuildError> {
        ts.iter().map(|t| self.ty(t)).collect()
    }

    fn fn_param(&self, p: &MFunctionParam) -> Result<ct::FunctionParam, RebuildError> {
        Ok(ct::FunctionParam {
            ty: Box::new(self.ty(&p.ty)?),
            name: p.name.map(|s| self.sym(s)).transpose()?,
            location: p.location.as_ref().map(|l| cl::FunctionParamLocation {
                range: self.range(&l.range),
                name_range: self.opt_range(&l.name_range),
            }),
        })
    }

    fn fn_params(&self, ps: &[MFunctionParam]) -> Result<Vec<ct::FunctionParam>, RebuildError> {
        ps.iter().map(|p| self.fn_param(p)).collect()
    }

    fn keyword_params(&self, ks: &[MKeywordParam]) -> Result<Vec<ct::KeywordParam>, RebuildError> {
        ks.iter()
            .map(|k| {
                Ok(ct::KeywordParam {
                    name: self.sym(k.name)?,
                    param: self.fn_param(&k.param)?,
                })
            })
            .collect()
    }

    pub(crate) fn function(&self, f: &MFunction) -> Result<ct::Function, RebuildError> {
        Ok(match f {
            MFunction::Typed(t) => ct::Function::Typed(ct::FunctionType {
                required_positionals: self.fn_params(&t.required_positionals)?,
                optional_positionals: self.fn_params(&t.optional_positionals)?,
                rest_positionals: t
                    .rest_positionals
                    .as_ref()
                    .map(|p| Ok::<_, RebuildError>(Box::new(self.fn_param(p)?)))
                    .transpose()?,
                trailing_positionals: self.fn_params(&t.trailing_positionals)?,
                required_keywords: self.keyword_params(&t.required_keywords)?,
                optional_keywords: self.keyword_params(&t.optional_keywords)?,
                rest_keywords: t
                    .rest_keywords
                    .as_ref()
                    .map(|p| Ok::<_, RebuildError>(Box::new(self.fn_param(p)?)))
                    .transpose()?,
                return_type: Box::new(self.ty(&t.return_type)?),
            }),
            MFunction::Untyped(u) => ct::Function::Untyped(ct::UntypedFunctionType {
                return_type: Box::new(self.ty(&u.return_type)?),
            }),
        })
    }

    fn block(&self, b: &MBlockType) -> Result<ct::BlockType, RebuildError> {
        Ok(ct::BlockType {
            required: b.required,
            function: self.function(&b.function)?,
            self_type: b
                .self_type
                .as_ref()
                .map(|t| Ok::<_, RebuildError>(Box::new(self.ty(t)?)))
                .transpose()?,
        })
    }

    fn type_param(&self, p: &MTypeParam) -> Result<TypeParam, RebuildError> {
        Ok(TypeParam {
            name: self.sym(p.name)?,
            variance: match p.variance {
                0 => Variance::Invariant,
                1 => Variance::Covariant,
                2 => Variance::Contravariant,
                v => return Err(corrupt(format!("unknown variance {v}"))),
            },
            upper_bound: p.upper_bound.as_ref().map(|t| self.ty(t)).transpose()?,
            lower_bound: p.lower_bound.as_ref().map(|t| self.ty(t)).transpose()?,
            default_type: p.default_type.as_ref().map(|t| self.ty(t)).transpose()?,
            unchecked: p.unchecked,
            location: p.location.as_ref().map(|l| cl::TypeParamLocation {
                range: self.range(&l.range),
                name_range: self.range(&l.name_range),
                variance_range: self.opt_range(&l.variance_range),
                unchecked_range: self.opt_range(&l.unchecked_range),
                upper_bound_range: self.opt_range(&l.upper_bound_range),
                lower_bound_range: self.opt_range(&l.lower_bound_range),
                default_range: self.opt_range(&l.default_range),
            }),
        })
    }

    fn type_params(&self, ps: &[MTypeParam]) -> Result<Vec<TypeParam>, RebuildError> {
        ps.iter().map(|p| self.type_param(p)).collect()
    }

    pub(crate) fn method_type(&self, m: &MMethodType) -> Result<MethodType, RebuildError> {
        Ok(MethodType {
            type_params: self.type_params(&m.type_params)?,
            function: self.function(&m.function)?,
            block: m.block.as_ref().map(|b| self.block(b)).transpose()?,
            location: m.location.as_ref().map(|l| cl::MethodTypeLocation {
                range: self.range(&l.range),
                type_range: self.range(&l.type_range),
                type_params_range: self.opt_range(&l.type_params_range),
            }),
        })
    }

    pub(crate) fn annotations(
        &self,
        a: &[MAnnotation],
    ) -> Result<Vec<crate::ast::annotation::Annotation>, RebuildError> {
        a.iter()
            .map(|a| {
                Ok(crate::ast::annotation::Annotation {
                    string: self.sym(a.string)?,
                    location: self.opt_range(&a.location),
                })
            })
            .collect()
    }

    fn comment(
        &self,
        c: &Option<MComment>,
    ) -> Result<Option<crate::ast::comment::Comment>, RebuildError> {
        c.as_ref()
            .map(|c| {
                Ok(crate::ast::comment::Comment {
                    string: self.sym(c.string)?,
                    location: self.opt_range(&c.location),
                })
            })
            .transpose()
    }

    fn visibility(&self, v: Option<u8>) -> Result<Option<cm::Visibility>, RebuildError> {
        v.map(|v| match v {
            0 => Ok(cm::Visibility::Public),
            1 => Ok(cm::Visibility::Private),
            v => Err(corrupt(format!("unknown visibility {v}"))),
        })
        .transpose()
    }

    fn ast_visibility(
        &self,
        v: Option<u8>,
    ) -> Result<Option<crate::ast::Visibility>, RebuildError> {
        v.map(|v| match v {
            0 => Ok(crate::ast::Visibility::Public),
            1 => Ok(crate::ast::Visibility::Private),
            v => Err(corrupt(format!("unknown visibility {v}"))),
        })
        .transpose()
    }

    fn mixin_fields(&self, m: &MMixinMember) -> Result<MixinFields, RebuildError> {
        Ok(MixinFields {
            name: self.tn(m.name)?,
            args: self.tys(&m.args)?,
            annotations: self.annotations(&m.annotations)?,
            location: m.location.as_ref().map(|l| cl::MixinMemberLocation {
                range: self.range(&l.range),
                keyword_range: self.range(&l.keyword_range),
                name_range: self.range(&l.name_range),
                args_range: self.opt_range(&l.args_range),
            }),
            source_file: self.opt_name(m.source_file)?,
            comment: self.comment(&m.comment)?,
        })
    }

    fn attr_fields(&self, m: &MAttrMember) -> Result<AttrFields, RebuildError> {
        Ok(AttrFields {
            name: self.sym(m.name)?,
            ty: self.ty(&m.ty)?,
            ivar_name: match &m.ivar_name {
                MIvarName::Unspecified => cm::IvarName::Unspecified,
                MIvarName::Empty => cm::IvarName::Empty,
                MIvarName::Name(s) => cm::IvarName::Name(self.sym(*s)?),
            },
            kind: match m.kind {
                0 => cm::AttributeKind::Instance,
                1 => cm::AttributeKind::Singleton,
                k => return Err(corrupt(format!("unknown attribute kind {k}"))),
            },
            annotations: self.annotations(&m.annotations)?,
            location: m.location.as_ref().map(|l| cl::AttributeMemberLocation {
                range: self.range(&l.range),
                keyword_range: self.range(&l.keyword_range),
                name_range: self.range(&l.name_range),
                colon_range: self.range(&l.colon_range),
                kind_range: self.opt_range(&l.kind_range),
                ivar_range: self.opt_range(&l.ivar_range),
                ivar_name_range: self.opt_range(&l.ivar_name_range),
                visibility_range: self.opt_range(&l.visibility_range),
            }),
            source_file: self.opt_name(m.source_file)?,
            comment: self.comment(&m.comment)?,
            visibility: self.ast_visibility(m.visibility)?,
        })
    }

    fn var_fields(&self, m: &MVarMember) -> Result<VarFields, RebuildError> {
        Ok(VarFields {
            name: self.sym(m.name)?,
            ty: self.ty(&m.ty)?,
            location: m.location.as_ref().map(|l| cl::VariableMemberLocation {
                range: self.range(&l.range),
                name_range: self.range(&l.name_range),
                colon_range: self.range(&l.colon_range),
                kind_range: self.opt_range(&l.kind_range),
            }),
            source_file: self.opt_name(m.source_file)?,
            comment: self.comment(&m.comment)?,
        })
    }

    fn member(&self, m: &MMember) -> Result<cd::Member, RebuildError> {
        Ok(match m {
            MMember::MethodDefinition(d) => {
                cd::Member::MethodDefinition(cm::MethodDefinitionMember {
                    name: self.sym(d.name)?,
                    kind: match d.kind {
                        0 => cm::MethodKind::Instance,
                        1 => cm::MethodKind::Singleton,
                        2 => cm::MethodKind::SingletonInstance,
                        k => return Err(corrupt(format!("unknown method kind {k}"))),
                    },
                    overloads: d
                        .overloads
                        .iter()
                        .map(|o| {
                            Ok(cm::MethodDefinitionOverload {
                                method_type: self.method_type(&o.method_type)?,
                                annotations: self.annotations(&o.annotations)?,
                            })
                        })
                        .collect::<Result<_, RebuildError>>()?,
                    annotations: self.annotations(&d.annotations)?,
                    overloading: d.overloading,
                    visibility: self.visibility(d.visibility)?,
                    location: d.location.as_ref().map(|l| cl::MethodDefinitionLocation {
                        range: self.range(&l.range),
                        keyword_range: self.range(&l.keyword_range),
                        name_range: self.range(&l.name_range),
                        kind_range: self.opt_range(&l.kind_range),
                        overloading_range: self.opt_range(&l.overloading_range),
                        visibility_range: self.opt_range(&l.visibility_range),
                    }),
                    source_file: self.opt_name(d.source_file)?,
                    comment: self.comment(&d.comment)?,
                })
            }
            MMember::Include(d) => {
                let MixinFields {
                    name,
                    args,
                    annotations,
                    location,
                    source_file,
                    comment,
                } = self.mixin_fields(d)?;
                cd::Member::Include(cm::IncludeMember {
                    name,
                    args,
                    annotations,
                    location,
                    source_file,
                    comment,
                })
            }
            MMember::Extend(d) => {
                let MixinFields {
                    name,
                    args,
                    annotations,
                    location,
                    source_file,
                    comment,
                } = self.mixin_fields(d)?;
                cd::Member::Extend(cm::ExtendMember {
                    name,
                    args,
                    annotations,
                    location,
                    source_file,
                    comment,
                })
            }
            MMember::Prepend(d) => {
                let MixinFields {
                    name,
                    args,
                    annotations,
                    location,
                    source_file,
                    comment,
                } = self.mixin_fields(d)?;
                cd::Member::Prepend(cm::PrependMember {
                    name,
                    args,
                    annotations,
                    location,
                    source_file,
                    comment,
                })
            }
            MMember::AttrReader(d) => {
                let AttrFields {
                    name,
                    ty,
                    ivar_name,
                    kind,
                    annotations,
                    location,
                    source_file,
                    comment,
                    visibility,
                } = self.attr_fields(d)?;
                cd::Member::AttrReader(cm::AttrReaderMember {
                    name,
                    ty,
                    ivar_name,
                    kind,
                    annotations,
                    location,
                    source_file,
                    comment,
                    visibility,
                })
            }
            MMember::AttrWriter(d) => {
                let AttrFields {
                    name,
                    ty,
                    ivar_name,
                    kind,
                    annotations,
                    location,
                    source_file,
                    comment,
                    visibility,
                } = self.attr_fields(d)?;
                cd::Member::AttrWriter(cm::AttrWriterMember {
                    name,
                    ty,
                    ivar_name,
                    kind,
                    annotations,
                    location,
                    source_file,
                    comment,
                    visibility,
                })
            }
            MMember::AttrAccessor(d) => {
                let AttrFields {
                    name,
                    ty,
                    ivar_name,
                    kind,
                    annotations,
                    location,
                    source_file,
                    comment,
                    visibility,
                } = self.attr_fields(d)?;
                cd::Member::AttrAccessor(cm::AttrAccessorMember {
                    name,
                    ty,
                    ivar_name,
                    kind,
                    annotations,
                    location,
                    source_file,
                    comment,
                    visibility,
                })
            }
            MMember::Public(d) => cd::Member::Public(cm::PublicMember {
                location: self.opt_range(&d.location),
            }),
            MMember::Private(d) => cd::Member::Private(cm::PrivateMember {
                location: self.opt_range(&d.location),
            }),
            MMember::Alias(d) => cd::Member::Alias(cm::AliasMember {
                new_name: self.sym(d.new_name)?,
                old_name: self.sym(d.old_name)?,
                kind: match d.kind {
                    0 => cm::AliasKind::Instance,
                    1 => cm::AliasKind::Singleton,
                    k => return Err(corrupt(format!("unknown alias kind {k}"))),
                },
                annotations: self.annotations(&d.annotations)?,
                location: d.location.as_ref().map(|l| cl::AliasMemberLocation {
                    range: self.range(&l.range),
                    keyword_range: self.range(&l.keyword_range),
                    new_name_range: self.range(&l.new_name_range),
                    old_name_range: self.range(&l.old_name_range),
                    new_kind_range: self.opt_range(&l.new_kind_range),
                    old_kind_range: self.opt_range(&l.old_kind_range),
                }),
                source_file: self.opt_name(d.source_file)?,
                comment: self.comment(&d.comment)?,
            }),
            MMember::InstanceVariable(d) => {
                let VarFields {
                    name,
                    ty,
                    location,
                    source_file,
                    comment,
                } = self.var_fields(d)?;
                cd::Member::InstanceVariable(cm::InstanceVariableMember {
                    name,
                    ty,
                    location,
                    source_file,
                    comment,
                })
            }
            MMember::ClassInstanceVariable(d) => {
                let VarFields {
                    name,
                    ty,
                    location,
                    source_file,
                    comment,
                } = self.var_fields(d)?;
                cd::Member::ClassInstanceVariable(cm::ClassInstanceVariableMember {
                    name,
                    ty,
                    location,
                    source_file,
                    comment,
                })
            }
            MMember::ClassVariable(d) => {
                let VarFields {
                    name,
                    ty,
                    location,
                    source_file,
                    comment,
                } = self.var_fields(d)?;
                cd::Member::ClassVariable(cm::ClassVariableMember {
                    name,
                    ty,
                    location,
                    source_file,
                    comment,
                })
            }
        })
    }

    fn class_super(&self, s: &MClassSuper) -> Result<cd::ClassSuper, RebuildError> {
        Ok(cd::ClassSuper {
            name: self.tn(s.name)?,
            args: self.tys(&s.args)?,
            location: s.location.as_ref().map(|l| cl::ClassSuperLocation {
                range: self.range(&l.range),
                name_range: self.range(&l.name_range),
                args_range: self.opt_range(&l.args_range),
            }),
            source_file: self.opt_name(s.source_file)?,
        })
    }

    fn module_self(&self, s: &MClassSuper) -> Result<cd::ModuleSelf, RebuildError> {
        Ok(cd::ModuleSelf {
            name: self.tn(s.name)?,
            args: self.tys(&s.args)?,
            location: s.location.as_ref().map(|l| cl::ModuleSelfLocation {
                range: self.range(&l.range),
                name_range: self.range(&l.name_range),
                args_range: self.opt_range(&l.args_range),
            }),
            source_file: self.opt_name(s.source_file)?,
        })
    }

    pub(crate) fn class_decl(
        &mut self,
        entries: &EntrySource<'_>,
        d: &Arc<MClassDeclaration>,
        own_ctx: &[Tn],
    ) -> Result<cd::ClassDeclaration, RebuildError> {
        let mut child_ctx: Vec<Tn> = own_ctx.to_vec();
        child_ctx.push(d.name);
        Ok(cd::ClassDeclaration {
            name: self.tn(d.name)?,
            type_params: self.type_params(&d.type_params)?,
            super_class: d
                .super_class
                .as_ref()
                .map(|s| self.class_super(s))
                .transpose()?,
            members: d
                .members
                .iter()
                .map(|m| {
                    Ok(match m {
                        MBodyMember::Member(m) => cd::ClassMember::Member(self.member(m)?),
                        MBodyMember::Declaration(r) => {
                            cd::ClassMember::Declaration(self.decl_ref(entries, r, &child_ctx)?)
                        }
                    })
                })
                .collect::<Result<_, RebuildError>>()?,
            annotations: self.annotations(&d.annotations)?,
            location: d.location.as_ref().map(|l| cl::ClassDeclarationLocation {
                range: self.range(&l.range),
                keyword_range: self.range(&l.keyword_range),
                name_range: self.range(&l.name_range),
                end_range: self.range(&l.end_range),
                type_params_range: self.opt_range(&l.type_params_range),
                lt_range: self.opt_range(&l.lt_range),
            }),
            source_file: self.opt_name(d.source_file)?,
            comment: self.comment(&d.comment)?,
        })
    }

    pub(crate) fn module_decl(
        &mut self,
        entries: &EntrySource<'_>,
        d: &Arc<MModuleDeclaration>,
        own_ctx: &[Tn],
    ) -> Result<cd::ModuleDeclaration, RebuildError> {
        let mut child_ctx: Vec<Tn> = own_ctx.to_vec();
        child_ctx.push(d.name);
        Ok(cd::ModuleDeclaration {
            name: self.tn(d.name)?,
            type_params: self.type_params(&d.type_params)?,
            self_types: d
                .self_types
                .iter()
                .map(|s| self.module_self(s))
                .collect::<Result<_, _>>()?,
            members: d
                .members
                .iter()
                .map(|m| {
                    Ok(match m {
                        MBodyMember::Member(m) => cd::ModuleMember::Member(self.member(m)?),
                        MBodyMember::Declaration(r) => {
                            cd::ModuleMember::Declaration(self.decl_ref(entries, r, &child_ctx)?)
                        }
                    })
                })
                .collect::<Result<_, RebuildError>>()?,
            annotations: self.annotations(&d.annotations)?,
            location: d.location.as_ref().map(|l| cl::ModuleDeclarationLocation {
                range: self.range(&l.range),
                keyword_range: self.range(&l.keyword_range),
                name_range: self.range(&l.name_range),
                end_range: self.range(&l.end_range),
                type_params_range: self.opt_range(&l.type_params_range),
                colon_range: self.opt_range(&l.colon_range),
                self_types_range: self.opt_range(&l.self_types_range),
            }),
            source_file: self.opt_name(d.source_file)?,
            comment: self.comment(&d.comment)?,
        })
    }

    pub(crate) fn interface_decl(
        &self,
        d: &Arc<MInterfaceDeclaration>,
    ) -> Result<cd::InterfaceDeclaration, RebuildError> {
        Ok(cd::InterfaceDeclaration {
            name: self.tn(d.name)?,
            type_params: self.type_params(&d.type_params)?,
            members: d
                .members
                .iter()
                .map(|m| self.member(m))
                .collect::<Result<_, _>>()?,
            annotations: self.annotations(&d.annotations)?,
            location: d
                .location
                .as_ref()
                .map(|l| cl::InterfaceDeclarationLocation {
                    range: self.range(&l.range),
                    keyword_range: self.range(&l.keyword_range),
                    name_range: self.range(&l.name_range),
                    end_range: self.range(&l.end_range),
                    type_params_range: self.opt_range(&l.type_params_range),
                }),
            source_file: self.opt_name(d.source_file)?,
            comment: self.comment(&d.comment)?,
        })
    }

    pub(crate) fn type_alias_decl(
        &self,
        d: &Arc<MTypeAliasDeclaration>,
    ) -> Result<cd::TypeAliasDeclaration, RebuildError> {
        Ok(cd::TypeAliasDeclaration {
            name: self.tn(d.name)?,
            type_params: self.type_params(&d.type_params)?,
            ty: self.ty(&d.ty)?,
            annotations: self.annotations(&d.annotations)?,
            location: d
                .location
                .as_ref()
                .map(|l| cl::TypeAliasDeclarationLocation {
                    range: self.range(&l.range),
                    keyword_range: self.range(&l.keyword_range),
                    name_range: self.range(&l.name_range),
                    eq_range: self.range(&l.eq_range),
                    type_params_range: self.opt_range(&l.type_params_range),
                }),
            source_file: self.opt_name(d.source_file)?,
            comment: self.comment(&d.comment)?,
        })
    }

    pub(crate) fn constant_decl(
        &self,
        d: &Arc<MConstantDeclaration>,
    ) -> Result<cd::ConstantDeclaration, RebuildError> {
        Ok(cd::ConstantDeclaration {
            name: self.tn(d.name)?,
            ty: self.ty(&d.ty)?,
            annotations: self.annotations(&d.annotations)?,
            location: d
                .location
                .as_ref()
                .map(|l| cl::ConstantDeclarationLocation {
                    range: self.range(&l.range),
                    name_range: self.range(&l.name_range),
                    colon_range: self.range(&l.colon_range),
                }),
            comment: self.comment(&d.comment)?,
        })
    }

    pub(crate) fn global_decl(
        &self,
        d: &Arc<MGlobalDeclaration>,
    ) -> Result<cd::GlobalDeclaration, RebuildError> {
        Ok(cd::GlobalDeclaration {
            name: self.sym(d.name)?,
            ty: self.ty(&d.ty)?,
            annotations: self.annotations(&d.annotations)?,
            location: d.location.as_ref().map(|l| cl::GlobalDeclarationLocation {
                range: self.range(&l.range),
                name_range: self.range(&l.name_range),
                colon_range: self.range(&l.colon_range),
            }),
            comment: self.comment(&d.comment)?,
        })
    }

    fn alias_decl_location(
        &self,
        l: &Option<MAliasDeclLoc>,
    ) -> Option<cl::AliasDeclarationLocation> {
        l.as_ref().map(|l| cl::AliasDeclarationLocation {
            range: self.range(&l.range),
            keyword_range: self.range(&l.keyword_range),
            new_name_range: self.range(&l.new_name_range),
            eq_range: self.range(&l.eq_range),
            old_name_range: self.range(&l.old_name_range),
        })
    }

    pub(crate) fn class_alias_decl(
        &self,
        d: &Arc<MClassAliasDeclaration>,
    ) -> Result<cd::ClassAliasDeclaration, RebuildError> {
        Ok(cd::ClassAliasDeclaration {
            new_name: self.tn(d.new_name)?,
            old_name: self.tn(d.old_name)?,
            annotations: self.annotations(&d.annotations)?,
            location: self.alias_decl_location(&d.location),
            source_file: self.opt_name(d.source_file)?,
            comment: self.comment(&d.comment)?,
        })
    }

    pub(crate) fn module_alias_decl(
        &self,
        d: &Arc<MClassAliasDeclaration>,
    ) -> Result<cd::ModuleAliasDeclaration, RebuildError> {
        Ok(cd::ModuleAliasDeclaration {
            new_name: self.tn(d.new_name)?,
            old_name: self.tn(d.old_name)?,
            annotations: self.annotations(&d.annotations)?,
            location: self.alias_decl_location(&d.location),
            source_file: self.opt_name(d.source_file)?,
            comment: self.comment(&d.comment)?,
        })
    }
}
