// ===== Auto-generated by scripts/generate_rbs_raw.rb =====
// ===== Source: vendor/ruby-rbs-sys/vendor/rbs/config.yml =====
// ===== Node count: 79 (includes injected Symbol) =====
// ===== DO NOT EDIT MANUALLY =====

use super::{Parser, RawHash, RawNodeList, RawString};
use ruby_rbs_sys::bindings::*;

/// Generated from config.yml enum: attribute_visibility
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttributeVisibility {
    Unspecified,
    Public,
    Private,
}

impl AttributeVisibility {
    pub fn from_raw(raw: u32) -> Self {
        if raw == rbs_attribute_visibility::RBS_ATTRIBUTE_VISIBILITY_UNSPECIFIED {
            AttributeVisibility::Unspecified
        } else if raw == rbs_attribute_visibility::RBS_ATTRIBUTE_VISIBILITY_PUBLIC {
            AttributeVisibility::Public
        } else if raw == rbs_attribute_visibility::RBS_ATTRIBUTE_VISIBILITY_PRIVATE {
            AttributeVisibility::Private
        } else {
            AttributeVisibility::Unspecified
        }
    }
}

/// Generated from config.yml enum: attribute_kind
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttributeKind {
    Instance,
    Singleton,
}

impl AttributeKind {
    pub fn from_raw(raw: u32) -> Self {
        if raw == rbs_attribute_kind::RBS_ATTRIBUTE_KIND_INSTANCE {
            AttributeKind::Instance
        } else if raw == rbs_attribute_kind::RBS_ATTRIBUTE_KIND_SINGLETON {
            AttributeKind::Singleton
        } else {
            AttributeKind::Instance
        }
    }
}

/// Generated from config.yml enum: alias_kind
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AliasKind {
    Instance,
    Singleton,
}

impl AliasKind {
    pub fn from_raw(raw: u32) -> Self {
        if raw == rbs_alias_kind::RBS_ALIAS_KIND_INSTANCE {
            AliasKind::Instance
        } else if raw == rbs_alias_kind::RBS_ALIAS_KIND_SINGLETON {
            AliasKind::Singleton
        } else {
            AliasKind::Instance
        }
    }
}

/// Generated from config.yml enum: method_definition_kind
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MethodDefinitionKind {
    Instance,
    Singleton,
    SingletonInstance,
}

impl MethodDefinitionKind {
    pub fn from_raw(raw: u32) -> Self {
        if raw == rbs_method_definition_kind::RBS_METHOD_DEFINITION_KIND_INSTANCE {
            MethodDefinitionKind::Instance
        } else if raw == rbs_method_definition_kind::RBS_METHOD_DEFINITION_KIND_SINGLETON {
            MethodDefinitionKind::Singleton
        } else if raw == rbs_method_definition_kind::RBS_METHOD_DEFINITION_KIND_SINGLETON_INSTANCE {
            MethodDefinitionKind::SingletonInstance
        } else {
            MethodDefinitionKind::Instance
        }
    }
}

/// Generated from config.yml enum: method_definition_visibility
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MethodDefinitionVisibility {
    Unspecified,
    Public,
    Private,
}

impl MethodDefinitionVisibility {
    pub fn from_raw(raw: u32) -> Self {
        if raw == rbs_method_definition_visibility::RBS_METHOD_DEFINITION_VISIBILITY_UNSPECIFIED {
            MethodDefinitionVisibility::Unspecified
        } else if raw == rbs_method_definition_visibility::RBS_METHOD_DEFINITION_VISIBILITY_PUBLIC {
            MethodDefinitionVisibility::Public
        } else if raw == rbs_method_definition_visibility::RBS_METHOD_DEFINITION_VISIBILITY_PRIVATE
        {
            MethodDefinitionVisibility::Private
        } else {
            MethodDefinitionVisibility::Unspecified
        }
    }
}

/// Generated from config.yml enum: type_param_variance
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TypeParamVariance {
    Invariant,
    Covariant,
    Contravariant,
}

impl TypeParamVariance {
    pub fn from_raw(raw: u32) -> Self {
        if raw == rbs_type_param_variance::RBS_TYPE_PARAM_VARIANCE_INVARIANT {
            TypeParamVariance::Invariant
        } else if raw == rbs_type_param_variance::RBS_TYPE_PARAM_VARIANCE_COVARIANT {
            TypeParamVariance::Covariant
        } else if raw == rbs_type_param_variance::RBS_TYPE_PARAM_VARIANCE_CONTRAVARIANT {
            TypeParamVariance::Contravariant
        } else {
            TypeParamVariance::Invariant
        }
    }
}

/// Classification of RBS type nodes.
/// All unsafe field extraction is done in classify_type().
#[derive(Debug)]
pub enum TypeKind<'a> {
    Alias {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
    },
    Any {
        todo: bool,
    },
    Bool,
    Bottom,
    Class,
    Instance,
    Nil,
    SelfType,
    Top,
    Void,
    Block {
        type_: *const rbs_node,
        required: bool,
        self_type: Option<*const rbs_node>,
    },
    ClassInstance {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
    },
    ClassSingleton {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
    },
    Function {
        required_positionals: RawNodeList<'a>,
        optional_positionals: RawNodeList<'a>,
        rest_positionals: Option<*const rbs_node>,
        trailing_positionals: RawNodeList<'a>,
        required_keywords: RawHash<'a>,
        optional_keywords: RawHash<'a>,
        rest_keywords: Option<*const rbs_node>,
        forwarding: Option<*const rbs_node>,
        return_type: *const rbs_node,
    },
    FunctionParam {
        type_: *const rbs_node,
        name: Option<*const rbs_ast_symbol>,
    },
    FunctionForwardingParam,
    Interface {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
    },
    Intersection {
        types: RawNodeList<'a>,
    },
    Literal {
        literal: *const rbs_node,
    },
    Optional {
        type_: *const rbs_node,
    },
    Proc {
        type_: *const rbs_node,
        block: Option<*const rbs_types_block>,
        self_type: Option<*const rbs_node>,
    },
    Record {
        all_fields: RawHash<'a>,
    },
    RecordField {
        type_: *const rbs_node,
        required: bool,
    },
    Tuple {
        types: RawNodeList<'a>,
    },
    Union {
        types: RawNodeList<'a>,
    },
    UntypedFunction {
        return_type: *const rbs_node,
    },
    Variable {
        name: *const rbs_ast_symbol,
    },
    /// Unknown or unhandled type node
    UnknownType(rbs_node_type::Type),
}

/// Classify a raw RBS node pointer into a TypeKind.
///
/// # Safety
/// All unsafe pointer access is contained within this function.
/// The caller passes a valid `*const rbs_node` and receives a safe enum.
/// The `_parser` argument is used solely to bind the returned `TypeKind`'s
/// lifetime to the parser's RBS arena.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn classify_type<'a>(_parser: &'a Parser, node: *const rbs_node) -> TypeKind<'a> {
    let node_type = unsafe { (*node).type_ };
    match node_type {
        rbs_node_type::RBS_TYPES_ALIAS => {
            let n = unsafe { &*(node as *const rbs_types_alias_t) };
            TypeKind::Alias {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
            }
        }
        rbs_node_type::RBS_TYPES_BASES_ANY => {
            let n = unsafe { &*(node as *const rbs_types_bases_any_t) };
            TypeKind::Any { todo: n.todo }
        }
        rbs_node_type::RBS_TYPES_BASES_BOOL => TypeKind::Bool,
        rbs_node_type::RBS_TYPES_BASES_BOTTOM => TypeKind::Bottom,
        rbs_node_type::RBS_TYPES_BASES_CLASS => TypeKind::Class,
        rbs_node_type::RBS_TYPES_BASES_INSTANCE => TypeKind::Instance,
        rbs_node_type::RBS_TYPES_BASES_NIL => TypeKind::Nil,
        rbs_node_type::RBS_TYPES_BASES_SELF => TypeKind::SelfType,
        rbs_node_type::RBS_TYPES_BASES_TOP => TypeKind::Top,
        rbs_node_type::RBS_TYPES_BASES_VOID => TypeKind::Void,
        rbs_node_type::RBS_TYPES_BLOCK => {
            let n = unsafe { &*(node as *const rbs_types_block_t) };
            TypeKind::Block {
                type_: n.type_ as *const rbs_node,
                required: n.required,
                self_type: if n.self_type.is_null() {
                    None
                } else {
                    Some(n.self_type as *const rbs_node)
                },
            }
        }
        rbs_node_type::RBS_TYPES_CLASS_INSTANCE => {
            let n = unsafe { &*(node as *const rbs_types_class_instance_t) };
            TypeKind::ClassInstance {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
            }
        }
        rbs_node_type::RBS_TYPES_CLASS_SINGLETON => {
            let n = unsafe { &*(node as *const rbs_types_class_singleton_t) };
            TypeKind::ClassSingleton {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
            }
        }
        rbs_node_type::RBS_TYPES_FUNCTION => {
            let n = unsafe { &*(node as *const rbs_types_function_t) };
            TypeKind::Function {
                required_positionals: unsafe { RawNodeList::from_raw(n.required_positionals) },
                optional_positionals: unsafe { RawNodeList::from_raw(n.optional_positionals) },
                rest_positionals: if n.rest_positionals.is_null() {
                    None
                } else {
                    Some(n.rest_positionals as *const rbs_node)
                },
                trailing_positionals: unsafe { RawNodeList::from_raw(n.trailing_positionals) },
                required_keywords: unsafe { RawHash::from_raw(n.required_keywords) },
                optional_keywords: unsafe { RawHash::from_raw(n.optional_keywords) },
                rest_keywords: if n.rest_keywords.is_null() {
                    None
                } else {
                    Some(n.rest_keywords as *const rbs_node)
                },
                forwarding: if n.forwarding.is_null() {
                    None
                } else {
                    Some(n.forwarding as *const rbs_node)
                },
                return_type: n.return_type as *const rbs_node,
            }
        }
        rbs_node_type::RBS_TYPES_FUNCTION_PARAM => {
            let n = unsafe { &*(node as *const rbs_types_function_param_t) };
            TypeKind::FunctionParam {
                type_: n.type_ as *const rbs_node,
                name: if n.name.is_null() {
                    None
                } else {
                    Some(n.name as *const rbs_ast_symbol)
                },
            }
        }
        rbs_node_type::RBS_TYPES_FUNCTION_FORWARDING_PARAM => TypeKind::FunctionForwardingParam,
        rbs_node_type::RBS_TYPES_INTERFACE => {
            let n = unsafe { &*(node as *const rbs_types_interface_t) };
            TypeKind::Interface {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
            }
        }
        rbs_node_type::RBS_TYPES_INTERSECTION => {
            let n = unsafe { &*(node as *const rbs_types_intersection_t) };
            TypeKind::Intersection {
                types: unsafe { RawNodeList::from_raw(n.types) },
            }
        }
        rbs_node_type::RBS_TYPES_LITERAL => {
            let n = unsafe { &*(node as *const rbs_types_literal_t) };
            TypeKind::Literal {
                literal: n.literal as *const rbs_node,
            }
        }
        rbs_node_type::RBS_TYPES_OPTIONAL => {
            let n = unsafe { &*(node as *const rbs_types_optional_t) };
            TypeKind::Optional {
                type_: n.type_ as *const rbs_node,
            }
        }
        rbs_node_type::RBS_TYPES_PROC => {
            let n = unsafe { &*(node as *const rbs_types_proc_t) };
            TypeKind::Proc {
                type_: n.type_ as *const rbs_node,
                block: if n.block.is_null() {
                    None
                } else {
                    Some(n.block as *const rbs_types_block)
                },
                self_type: if n.self_type.is_null() {
                    None
                } else {
                    Some(n.self_type as *const rbs_node)
                },
            }
        }
        rbs_node_type::RBS_TYPES_RECORD => {
            let n = unsafe { &*(node as *const rbs_types_record_t) };
            TypeKind::Record {
                all_fields: unsafe { RawHash::from_raw(n.all_fields) },
            }
        }
        rbs_node_type::RBS_TYPES_RECORD_FIELD_TYPE => {
            let n = unsafe { &*(node as *const rbs_types_record_field_type_t) };
            TypeKind::RecordField {
                type_: n.type_ as *const rbs_node,
                required: n.required,
            }
        }
        rbs_node_type::RBS_TYPES_TUPLE => {
            let n = unsafe { &*(node as *const rbs_types_tuple_t) };
            TypeKind::Tuple {
                types: unsafe { RawNodeList::from_raw(n.types) },
            }
        }
        rbs_node_type::RBS_TYPES_UNION => {
            let n = unsafe { &*(node as *const rbs_types_union_t) };
            TypeKind::Union {
                types: unsafe { RawNodeList::from_raw(n.types) },
            }
        }
        rbs_node_type::RBS_TYPES_UNTYPED_FUNCTION => {
            let n = unsafe { &*(node as *const rbs_types_untyped_function_t) };
            TypeKind::UntypedFunction {
                return_type: n.return_type as *const rbs_node,
            }
        }
        rbs_node_type::RBS_TYPES_VARIABLE => {
            let n = unsafe { &*(node as *const rbs_types_variable_t) };
            TypeKind::Variable {
                name: n.name as *const rbs_ast_symbol,
            }
        }
        other => TypeKind::UnknownType(other),
    }
}

/// Classification of RBS declaration nodes.
#[derive(Debug)]
pub enum DeclKind<'a> {
    Class {
        name: *const rbs_type_name,
        type_params: RawNodeList<'a>,
        super_class: Option<*const rbs_ast_declarations_class_super>,
        members: RawNodeList<'a>,
        annotations: RawNodeList<'a>,
    },
    ClassSuper {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
    },
    ClassAlias {
        new_name: *const rbs_type_name,
        old_name: *const rbs_type_name,
        annotations: RawNodeList<'a>,
    },
    Constant {
        name: *const rbs_type_name,
        type_: *const rbs_node,
        annotations: RawNodeList<'a>,
    },
    Global {
        name: *const rbs_ast_symbol,
        type_: *const rbs_node,
        annotations: RawNodeList<'a>,
    },
    Interface {
        name: *const rbs_type_name,
        type_params: RawNodeList<'a>,
        members: RawNodeList<'a>,
        annotations: RawNodeList<'a>,
    },
    Module {
        name: *const rbs_type_name,
        type_params: RawNodeList<'a>,
        self_types: RawNodeList<'a>,
        members: RawNodeList<'a>,
        annotations: RawNodeList<'a>,
    },
    ModuleSelf {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
    },
    ModuleAlias {
        new_name: *const rbs_type_name,
        old_name: *const rbs_type_name,
        annotations: RawNodeList<'a>,
    },
    TypeAlias {
        name: *const rbs_type_name,
        type_params: RawNodeList<'a>,
        type_: *const rbs_node,
        annotations: RawNodeList<'a>,
    },
    /// Unknown or unhandled declaration node
    UnknownDecl(rbs_node_type::Type),
}

#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn classify_decl<'a>(_parser: &'a Parser, node: *const rbs_node) -> DeclKind<'a> {
    let node_type = unsafe { (*node).type_ };
    match node_type {
        rbs_node_type::RBS_AST_DECLARATIONS_CLASS => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_class_t) };
            DeclKind::Class {
                name: n.name as *const rbs_type_name,
                type_params: unsafe { RawNodeList::from_raw(n.type_params) },
                super_class: if n.super_class.is_null() {
                    None
                } else {
                    Some(n.super_class as *const rbs_ast_declarations_class_super)
                },
                members: unsafe { RawNodeList::from_raw(n.members) },
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_CLASS_SUPER => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_class_super_t) };
            DeclKind::ClassSuper {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_CLASS_ALIAS => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_class_alias_t) };
            DeclKind::ClassAlias {
                new_name: n.new_name as *const rbs_type_name,
                old_name: n.old_name as *const rbs_type_name,
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_CONSTANT => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_constant_t) };
            DeclKind::Constant {
                name: n.name as *const rbs_type_name,
                type_: n.type_ as *const rbs_node,
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_GLOBAL => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_global_t) };
            DeclKind::Global {
                name: n.name as *const rbs_ast_symbol,
                type_: n.type_ as *const rbs_node,
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_INTERFACE => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_interface_t) };
            DeclKind::Interface {
                name: n.name as *const rbs_type_name,
                type_params: unsafe { RawNodeList::from_raw(n.type_params) },
                members: unsafe { RawNodeList::from_raw(n.members) },
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_MODULE => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_module_t) };
            DeclKind::Module {
                name: n.name as *const rbs_type_name,
                type_params: unsafe { RawNodeList::from_raw(n.type_params) },
                self_types: unsafe { RawNodeList::from_raw(n.self_types) },
                members: unsafe { RawNodeList::from_raw(n.members) },
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_MODULE_SELF => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_module_self_t) };
            DeclKind::ModuleSelf {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_MODULE_ALIAS => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_module_alias_t) };
            DeclKind::ModuleAlias {
                new_name: n.new_name as *const rbs_type_name,
                old_name: n.old_name as *const rbs_type_name,
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_DECLARATIONS_TYPE_ALIAS => {
            let n = unsafe { &*(node as *const rbs_ast_declarations_type_alias_t) };
            DeclKind::TypeAlias {
                name: n.name as *const rbs_type_name,
                type_params: unsafe { RawNodeList::from_raw(n.type_params) },
                type_: n.type_ as *const rbs_node,
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        other => DeclKind::UnknownDecl(other),
    }
}

/// Classification of RBS member nodes.
#[derive(Debug)]
pub enum MemberKind<'a> {
    Alias {
        new_name: *const rbs_ast_symbol,
        old_name: *const rbs_ast_symbol,
        kind: AliasKind,
        annotations: RawNodeList<'a>,
    },
    AttrAccessor {
        name: *const rbs_ast_symbol,
        type_: *const rbs_node,
        ivar_name: rbs_attr_ivar_name,
        kind: AttributeKind,
        annotations: RawNodeList<'a>,
        visibility: AttributeVisibility,
    },
    AttrReader {
        name: *const rbs_ast_symbol,
        type_: *const rbs_node,
        ivar_name: rbs_attr_ivar_name,
        kind: AttributeKind,
        annotations: RawNodeList<'a>,
        visibility: AttributeVisibility,
    },
    AttrWriter {
        name: *const rbs_ast_symbol,
        type_: *const rbs_node,
        ivar_name: rbs_attr_ivar_name,
        kind: AttributeKind,
        annotations: RawNodeList<'a>,
        visibility: AttributeVisibility,
    },
    ClassInstanceVariable {
        name: *const rbs_ast_symbol,
        type_: *const rbs_node,
    },
    ClassVariable {
        name: *const rbs_ast_symbol,
        type_: *const rbs_node,
    },
    Extend {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
        annotations: RawNodeList<'a>,
    },
    Include {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
        annotations: RawNodeList<'a>,
    },
    InstanceVariable {
        name: *const rbs_ast_symbol,
        type_: *const rbs_node,
    },
    MethodDefinition {
        name: *const rbs_ast_symbol,
        kind: MethodDefinitionKind,
        overloads: RawNodeList<'a>,
        annotations: RawNodeList<'a>,
        overloading: bool,
        visibility: MethodDefinitionVisibility,
    },
    MethodDefinitionOverload {
        annotations: RawNodeList<'a>,
        method_type: *const rbs_node,
    },
    Prepend {
        name: *const rbs_type_name,
        args: RawNodeList<'a>,
        annotations: RawNodeList<'a>,
    },
    Private,
    Public,
    NestedDecl(*const rbs_node),
    /// Unknown or unhandled member node
    UnknownMember(rbs_node_type::Type),
}

#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn classify_member<'a>(_parser: &'a Parser, node: *const rbs_node) -> MemberKind<'a> {
    let node_type = unsafe { (*node).type_ };
    match node_type {
        rbs_node_type::RBS_AST_MEMBERS_ALIAS => {
            let n = unsafe { &*(node as *const rbs_ast_members_alias_t) };
            MemberKind::Alias {
                new_name: n.new_name as *const rbs_ast_symbol,
                old_name: n.old_name as *const rbs_ast_symbol,
                kind: AliasKind::from_raw(n.kind),
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_ATTR_ACCESSOR => {
            let n = unsafe { &*(node as *const rbs_ast_members_attr_accessor_t) };
            MemberKind::AttrAccessor {
                name: n.name as *const rbs_ast_symbol,
                type_: n.type_ as *const rbs_node,
                ivar_name: n.ivar_name,
                kind: AttributeKind::from_raw(n.kind),
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
                visibility: AttributeVisibility::from_raw(n.visibility),
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_ATTR_READER => {
            let n = unsafe { &*(node as *const rbs_ast_members_attr_reader_t) };
            MemberKind::AttrReader {
                name: n.name as *const rbs_ast_symbol,
                type_: n.type_ as *const rbs_node,
                ivar_name: n.ivar_name,
                kind: AttributeKind::from_raw(n.kind),
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
                visibility: AttributeVisibility::from_raw(n.visibility),
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_ATTR_WRITER => {
            let n = unsafe { &*(node as *const rbs_ast_members_attr_writer_t) };
            MemberKind::AttrWriter {
                name: n.name as *const rbs_ast_symbol,
                type_: n.type_ as *const rbs_node,
                ivar_name: n.ivar_name,
                kind: AttributeKind::from_raw(n.kind),
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
                visibility: AttributeVisibility::from_raw(n.visibility),
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_CLASS_INSTANCE_VARIABLE => {
            let n = unsafe { &*(node as *const rbs_ast_members_class_instance_variable_t) };
            MemberKind::ClassInstanceVariable {
                name: n.name as *const rbs_ast_symbol,
                type_: n.type_ as *const rbs_node,
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_CLASS_VARIABLE => {
            let n = unsafe { &*(node as *const rbs_ast_members_class_variable_t) };
            MemberKind::ClassVariable {
                name: n.name as *const rbs_ast_symbol,
                type_: n.type_ as *const rbs_node,
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_EXTEND => {
            let n = unsafe { &*(node as *const rbs_ast_members_extend_t) };
            MemberKind::Extend {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_INCLUDE => {
            let n = unsafe { &*(node as *const rbs_ast_members_include_t) };
            MemberKind::Include {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_INSTANCE_VARIABLE => {
            let n = unsafe { &*(node as *const rbs_ast_members_instance_variable_t) };
            MemberKind::InstanceVariable {
                name: n.name as *const rbs_ast_symbol,
                type_: n.type_ as *const rbs_node,
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_METHOD_DEFINITION => {
            let n = unsafe { &*(node as *const rbs_ast_members_method_definition_t) };
            MemberKind::MethodDefinition {
                name: n.name as *const rbs_ast_symbol,
                kind: MethodDefinitionKind::from_raw(n.kind),
                overloads: unsafe { RawNodeList::from_raw(n.overloads) },
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
                overloading: n.overloading,
                visibility: MethodDefinitionVisibility::from_raw(n.visibility),
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_METHOD_DEFINITION_OVERLOAD => {
            let n = unsafe { &*(node as *const rbs_ast_members_method_definition_overload_t) };
            MemberKind::MethodDefinitionOverload {
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
                method_type: n.method_type as *const rbs_node,
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_PREPEND => {
            let n = unsafe { &*(node as *const rbs_ast_members_prepend_t) };
            MemberKind::Prepend {
                name: n.name as *const rbs_type_name,
                args: unsafe { RawNodeList::from_raw(n.args) },
                annotations: unsafe { RawNodeList::from_raw(n.annotations) },
            }
        }
        rbs_node_type::RBS_AST_MEMBERS_PRIVATE => MemberKind::Private,
        rbs_node_type::RBS_AST_MEMBERS_PUBLIC => MemberKind::Public,
        rbs_node_type::RBS_AST_DECLARATIONS_CLASS
        | rbs_node_type::RBS_AST_DECLARATIONS_MODULE
        | rbs_node_type::RBS_AST_DECLARATIONS_INTERFACE
        | rbs_node_type::RBS_AST_DECLARATIONS_CONSTANT
        | rbs_node_type::RBS_AST_DECLARATIONS_GLOBAL
        | rbs_node_type::RBS_AST_DECLARATIONS_TYPE_ALIAS
        | rbs_node_type::RBS_AST_DECLARATIONS_CLASS_ALIAS
        | rbs_node_type::RBS_AST_DECLARATIONS_MODULE_ALIAS => MemberKind::NestedDecl(node),
        other => MemberKind::UnknownMember(other),
    }
}

/// Classification of RBS Ruby annotation nodes.
///
/// Fields are intentionally not exposed yet; this enum exists so
/// config.yml annotation variants cannot silently drift out of coverage.
#[derive(Debug)]
pub enum AnnotationKind {
    NodeTypeAssertion,
    ColonMethodTypeAnnotation,
    MethodTypesAnnotation,
    SkipAnnotation,
    ReturnTypeAnnotation,
    TypeApplicationAnnotation,
    InstanceVariableAnnotation,
    ClassAliasAnnotation,
    ModuleAliasAnnotation,
    ModuleSelfAnnotation,
    ParamTypeAnnotation,
    SplatParamTypeAnnotation,
    DoubleSplatParamTypeAnnotation,
    BlockParamTypeAnnotation,
    UnknownAnnotation(rbs_node_type::Type),
}

#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn classify_annotation(_parser: &Parser, node: *const rbs_node) -> AnnotationKind {
    let node_type = unsafe { (*node).type_ };
    match node_type {
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_NODE_TYPE_ASSERTION => {
            AnnotationKind::NodeTypeAssertion
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_COLON_METHOD_TYPE_ANNOTATION => {
            AnnotationKind::ColonMethodTypeAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_METHOD_TYPES_ANNOTATION => {
            AnnotationKind::MethodTypesAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_SKIP_ANNOTATION => AnnotationKind::SkipAnnotation,
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_RETURN_TYPE_ANNOTATION => {
            AnnotationKind::ReturnTypeAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_TYPE_APPLICATION_ANNOTATION => {
            AnnotationKind::TypeApplicationAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_INSTANCE_VARIABLE_ANNOTATION => {
            AnnotationKind::InstanceVariableAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_CLASS_ALIAS_ANNOTATION => {
            AnnotationKind::ClassAliasAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_MODULE_ALIAS_ANNOTATION => {
            AnnotationKind::ModuleAliasAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_MODULE_SELF_ANNOTATION => {
            AnnotationKind::ModuleSelfAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_PARAM_TYPE_ANNOTATION => {
            AnnotationKind::ParamTypeAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_SPLAT_PARAM_TYPE_ANNOTATION => {
            AnnotationKind::SplatParamTypeAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_DOUBLE_SPLAT_PARAM_TYPE_ANNOTATION => {
            AnnotationKind::DoubleSplatParamTypeAnnotation
        }
        rbs_node_type::RBS_AST_RUBY_ANNOTATIONS_BLOCK_PARAM_TYPE_ANNOTATION => {
            AnnotationKind::BlockParamTypeAnnotation
        }
        other => AnnotationKind::UnknownAnnotation(other),
    }
}

/// Classification of structural RBS nodes (MethodType, Signature, etc.).
#[derive(Debug)]
pub enum StructuralKind<'a> {
    Annotation {
        string: RawString<'a>,
    },
    Bool {
        value: bool,
    },
    Comment {
        string: RawString<'a>,
    },
    Use {
        clauses: RawNodeList<'a>,
    },
    UseSingleClause {
        type_name: *const rbs_type_name,
        new_name: Option<*const rbs_ast_symbol>,
    },
    UseWildcardClause {
        rbs_namespace: *const rbs_namespace,
    },
    TypeParam {
        name: *const rbs_ast_symbol,
        variance: TypeParamVariance,
        upper_bound: Option<*const rbs_node>,
        lower_bound: Option<*const rbs_node>,
        default_type: Option<*const rbs_node>,
        unchecked: bool,
    },
    Integer {
        string_representation: RawString<'a>,
    },
    String {
        string: RawString<'a>,
    },
    Method {
        type_params: RawNodeList<'a>,
        type_: *const rbs_node,
        block: Option<*const rbs_types_block>,
    },
    Namespace {
        path: RawNodeList<'a>,
        absolute: bool,
    },
    Signature {
        directives: RawNodeList<'a>,
        declarations: RawNodeList<'a>,
    },
    TypeName {
        rbs_namespace: *const rbs_namespace,
        name: *const rbs_ast_symbol,
    },
    Symbol,
    UnknownStructural(rbs_node_type::Type),
}

#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn classify_structural<'a>(_parser: &'a Parser, node: *const rbs_node) -> StructuralKind<'a> {
    let node_type = unsafe { (*node).type_ };
    match node_type {
        rbs_node_type::RBS_AST_ANNOTATION => {
            let n = unsafe { &*(node as *const rbs_ast_annotation_t) };
            StructuralKind::Annotation {
                string: unsafe { RawString::from_raw(n.string) },
            }
        }
        rbs_node_type::RBS_AST_BOOL => {
            let n = unsafe { &*(node as *const rbs_ast_bool_t) };
            StructuralKind::Bool { value: n.value }
        }
        rbs_node_type::RBS_AST_COMMENT => {
            let n = unsafe { &*(node as *const rbs_ast_comment_t) };
            StructuralKind::Comment {
                string: unsafe { RawString::from_raw(n.string) },
            }
        }
        rbs_node_type::RBS_AST_DIRECTIVES_USE => {
            let n = unsafe { &*(node as *const rbs_ast_directives_use_t) };
            StructuralKind::Use {
                clauses: unsafe { RawNodeList::from_raw(n.clauses) },
            }
        }
        rbs_node_type::RBS_AST_DIRECTIVES_USE_SINGLE_CLAUSE => {
            let n = unsafe { &*(node as *const rbs_ast_directives_use_single_clause_t) };
            StructuralKind::UseSingleClause {
                type_name: n.type_name as *const rbs_type_name,
                new_name: if n.new_name.is_null() {
                    None
                } else {
                    Some(n.new_name as *const rbs_ast_symbol)
                },
            }
        }
        rbs_node_type::RBS_AST_DIRECTIVES_USE_WILDCARD_CLAUSE => {
            let n = unsafe { &*(node as *const rbs_ast_directives_use_wildcard_clause_t) };
            StructuralKind::UseWildcardClause {
                rbs_namespace: n.rbs_namespace as *const rbs_namespace,
            }
        }
        rbs_node_type::RBS_AST_TYPE_PARAM => {
            let n = unsafe { &*(node as *const rbs_ast_type_param_t) };
            StructuralKind::TypeParam {
                name: n.name as *const rbs_ast_symbol,
                variance: TypeParamVariance::from_raw(n.variance),
                upper_bound: if n.upper_bound.is_null() {
                    None
                } else {
                    Some(n.upper_bound as *const rbs_node)
                },
                lower_bound: if n.lower_bound.is_null() {
                    None
                } else {
                    Some(n.lower_bound as *const rbs_node)
                },
                default_type: if n.default_type.is_null() {
                    None
                } else {
                    Some(n.default_type as *const rbs_node)
                },
                unchecked: n.unchecked,
            }
        }
        rbs_node_type::RBS_AST_INTEGER => {
            let n = unsafe { &*(node as *const rbs_ast_integer_t) };
            StructuralKind::Integer {
                string_representation: unsafe { RawString::from_raw(n.string_representation) },
            }
        }
        rbs_node_type::RBS_AST_STRING => {
            let n = unsafe { &*(node as *const rbs_ast_string_t) };
            StructuralKind::String {
                string: unsafe { RawString::from_raw(n.string) },
            }
        }
        rbs_node_type::RBS_METHOD_TYPE => {
            let n = unsafe { &*(node as *const rbs_method_type_t) };
            StructuralKind::Method {
                type_params: unsafe { RawNodeList::from_raw(n.type_params) },
                type_: n.type_ as *const rbs_node,
                block: if n.block.is_null() {
                    None
                } else {
                    Some(n.block as *const rbs_types_block)
                },
            }
        }
        rbs_node_type::RBS_NAMESPACE => {
            let n = unsafe { &*(node as *const rbs_namespace_t) };
            StructuralKind::Namespace {
                path: unsafe { RawNodeList::from_raw(n.path) },
                absolute: n.absolute,
            }
        }
        rbs_node_type::RBS_SIGNATURE => {
            let n = unsafe { &*(node as *const rbs_signature_t) };
            StructuralKind::Signature {
                directives: unsafe { RawNodeList::from_raw(n.directives) },
                declarations: unsafe { RawNodeList::from_raw(n.declarations) },
            }
        }
        rbs_node_type::RBS_TYPE_NAME => {
            let n = unsafe { &*(node as *const rbs_type_name_t) };
            StructuralKind::TypeName {
                rbs_namespace: n.rbs_namespace as *const rbs_namespace,
                name: n.name as *const rbs_ast_symbol,
            }
        }
        rbs_node_type::RBS_AST_SYMBOL => StructuralKind::Symbol,
        other => StructuralKind::UnknownStructural(other),
    }
}

/// Total node count from config.yml. Use in tests to detect drift.
pub const RBS_CONFIG_NODE_COUNT: usize = 79;
pub const RBS_CONFIG_TYPE_NODE_COUNT: usize = 27;
pub const RBS_CONFIG_DECL_NODE_COUNT: usize = 10;
pub const RBS_CONFIG_MEMBER_NODE_COUNT: usize = 14;
pub const RBS_CONFIG_ANNOTATION_NODE_COUNT: usize = 14;
pub const RBS_CONFIG_STRUCTURAL_NODE_COUNT: usize = 14;
pub const RBS_DECLARATIONS_T_NODE_COUNT: usize = 8;
